### ISSUE TITLE
Metadata format should be compatible w/ github et al

### ISSUE THREAD

**Issue by datenimperator** [gma/nesta#142]
[[Copied from here…](https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents)]

Many blogging websites, like [Jekyll](http://jekyllrb.com) with [GitHub Pages](http://pages.github.com), depend on some YAML-formatted metadata at the beginning of your post. You know, the stuff that goes between dashes like this:

``` yaml

---
layout: post
title: Blogging Like a Boss

---
```

Nesta should probably support that metadata format and deprecate the other style.
